version: "0.1.0"

services:
  main_app:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/bash -c "sleep 5 && python -m alembic upgrade head && python -m uvicorn main:main_app --reload --host 0.0.0.0 --port 8000"
    ports:
      - 8001:8000
    env_file:
      - .env.docker
    stdin_open: true
    tty: true
    depends_on:
      - db
      - adminer

  db:
    image: postgis/postgis:latest
    ports:
      - 6432:5432
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_rest
    volumes:
      - db_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db_data: