[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.115.6"
uvicorn = {extras = ["standard"], version = "^0.34.0"}
pydantic = {extras = ["email"], version = "^2.10.3"}
pydantic-settings = "^2.7.0"
sqlalchemy = {extras = ["asyncio"], version = "^2.0.36"}
asyncpg = "^0.30.0"
alembic = "^1.14.0"
black = "^24.10.0"
orjson = "^3.10.12"
geoalchemy2 = "^0.17.0"
shapely = "^2.0.6"
pytest = "^8.3.4"
httpx = "^0.28.1"
psycopg2 = "^2.9.10"
pytest-asyncio = "^0.25.3"

[tool.poetry.group.dev.dependencies]
black = "^24.10.0"

